from dataclasses import dataclass
from xmlrpc import client
from mcp.server.fastmcp import FastMCP, Image
import inspect, logging, matplotlib.pyplot as plt, base64, os, mimetypes, io, mcp
from typing import Dict, Any
from mcp.types import CallToolResult, TextContent, ImageContent
from mcp_ui_server import UIMetadataKey, UIResource
from tools.figureOchestrator.figToolDescriptions import FigToolPrompts
from adapters.postgresAdapter import PostgresAdapter
from tools.queryOrchestrator.postgresHelperFxns import PostgresHelperFxns
from utils.config import Configuration
from tools.figureOchestrator.figSessionDataClasses import (
    BarChartSessionState, 
    PieChartSessionState, 
    HistogramSessionState
)
from tools.figureOchestrator.figSessionSteps import (
    BarChartSteps, 
    PieChartSteps, 
    HistogramSteps
)
from mcp_ui_server import create_ui_resource
from fastmcp import Client
from fastmcp.client.transports import FastMCPTransport
from mcp.client.session import ClientSession
from mcp.client.sse import sse_client
from PIL import Image as PILImage
from acontext import AcontextClient, FileUpload

def register_fig_orchestration_tools(mcp: FastMCP):
    adapter = PostgresAdapter(config=Configuration.DB_CONFIG)
    figure_tools = FigOchestrationTools(mcp, adapter)
    available_tools = [name for name, func in inspect.getmembers(figure_tools, predicate=inspect.ismethod) if not name.startswith('_')]
    #logging.info(f"Available figure orchestration tools: {available_tools}")
    for tool_name in available_tools:
        logging.info(f"Registering figure orchestration tool: {tool_name}")
        mcp.add_tool(
                getattr(figure_tools, tool_name),
                name=tool_name,
                description=getattr(FigToolPrompts, tool_name, "No description available.")
        )

BARCHARTSESSION : Dict[str, BarChartSessionState] = {}
PIECHARTSESSION: Dict[str, PieChartSessionState] = {}
HISTOGRAMSESSION: Dict[str, HistogramSessionState] = {}

class FigOchestrationTools:

    def __init__(self, mcp: FastMCP, adapter: PostgresAdapter):
        self.mcp = mcp
        self.adapter = adapter

    async def show_dashboard(self) -> list[UIResource]:
        """Display a sample dashboard with metrics."""
        svg_path = f"/Users/kushaldevgun/Downloads/images/bar_chart.svg"
        svg_code = None
        with open(svg_path, "rb") as f:
            svg_code = f.read()
        try:
            dashboard_html = f"""
            <!DOCTYPE html>
            <html lang="en">
            <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">

            <style>
                body {{
                    margin: 0;
                    padding: 40px;
                    background: linear-gradient(135deg, #eef2ff, #f8fafc);
                    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
                    display: flex;
                    justify-content: center;
                }}

                .dashboard-container {{
                    max-width: 900px;
                    width: 100%;
                    background: white;
                    border-radius: 16px;
                    padding: 32px;
                    box-shadow: 0 8px 24px rgba(0,0,0,0.08);
                    text-align: center;
                }}

                h1 {{
                    margin-bottom: 24px;
                    font-size: 28px;
                    color: #1f2937;
                }}

                .chart-wrapper {{
                    width: 100%;
                    overflow: hidden;
                }}

                .chart-wrapper svg {{
                    width: 100% !important;
                    height: auto !important;
                }}

                .footer {{
                    margin-top: 20px;
                    font-size: 12px;
                    color: #6b7280;
                }}
            </style>
            </head>

            <body>
                <div class="dashboard-container">
                    <h1>HR Performance Dashboard</h1>

                    <div class="chart-wrapper">
                        {svg_code.decode('utf-8')}
                    </div>
                    <div class="footer">Generated by Fig Orchestrator</div>
                </div>
            </body>
            </html>
            """
        
            ui_resource = create_ui_resource({
                "uri": "ui://dashboard/main",
                "content": {
                    "type": "rawHtml",
                    "htmlString": dashboard_html
                },
                "encoding": "text",
            })
            return [ui_resource]
        except Exception as e:
            logging.error(f"Error processing image: {e}")
            await self.mcp.get_context().session.send_log_message("error", f"Error processing image: {e}")
            return [create_ui_resource({
                "uri": "ui://dashboard/error",
                "content": {
                    "type": "rawHtml",
                    "htmlString": f"<html><body><h1>Error loading dashboard</h1><p>{e}</p></body></html>"
                },
                "encoding": "text"
            })]
    
    async def plot_bar_chart(self, session_state: BarChartSessionState) -> CallToolResult:
        
        def text(msg: str, is_error: bool = False) -> CallToolResult:
            return CallToolResult(
                content=[TextContent(type="text", text=msg)],
                isError=is_error,
            )

        def decide_step(session_state: BarChartSessionState) -> str:
            has_table_name = bool(session_state.table_name)
            has_column_name = bool(session_state.column_name)
            if not has_table_name:
                return BarChartSteps.ASK_TABLE_NAME.value
            elif not has_column_name:
                return BarChartSteps.ASK_COLUMN.value
            else:
                return BarChartSteps.GENERATE_CHART.value

        sessions = BARCHARTSESSION.setdefault(session_state.session_id, session_state)
        if session_state.table_name is not None:
            sessions.table_name = session_state.table_name
        if session_state.column_name is not None:
            sessions.column_name = session_state.column_name

        sessions.step = decide_step(sessions)

        if sessions.step == BarChartSteps.ASK_TABLE_NAME.value:
            return text("Please provide the name of the table for which you want to generate the bar chart.")

        if sessions.step == BarChartSteps.ASK_COLUMN.value:
            ok = PostgresHelperFxns(adapter=self.adapter).check_table_exists(sessions.table_name)
            if not ok:
                BARCHARTSESSION.pop(sessions.session_id, None)
                return text(f'Table "{sessions.table_name}" does not exist. Please check the table name and try again.', is_error=True)
            return text("Please provide the column for which you want to generate the bar chart.")

        if sessions.step == BarChartSteps.GENERATE_CHART.value:
            column_data = PostgresHelperFxns(adapter=self.adapter).fetch_column_data(sessions.table_name, sessions.column_name)
            if not column_data:
                return text(f'No data found for column "{sessions.column_name}" in table "{sessions.table_name}".', is_error=True)

            unique_values = [row[sessions.column_name] for row in column_data]
            counts = [row["count"] for row in column_data]

            try:
                plt.rcParams['svg.fonttype'] = 'none'
                plt.figure(figsize=(10, 6))
                plt.bar(unique_values, counts)
                plt.xlabel(sessions.column_name, fontsize=12)
                plt.ylabel("Values", fontsize=12)
                plt.title("Bar Chart", fontsize=14)
                #plt.tight_layout()

                sid = sessions.session_id
                #buf = io.BytesIO()
                png_img_path = f"/Users/kushaldevgun/Downloads/images/bar_chart.png"
                svg_img_path = f"/Users/kushaldevgun/Downloads/images/bar_chart.svg"
                plt.savefig(png_img_path, format = 'png')
                plt.savefig(svg_img_path, format="svg", bbox_inches='tight')
                plt.close()
                with open(png_img_path, "rb") as f:
                    png_bytes = f.read()
                b64 = base64.b64encode(png_bytes).decode("utf-8")
                mime, _ = mimetypes.guess_type(png_img_path)
                col = sessions.column_name
                await self.mcp.get_context().session.send_log_message("critical", f"Generated bar chart for column '{col}' with unique values {unique_values} and counts {counts}. Image saved at {png_img_path}")
                # try:
                #     sse_url ="http://127.0.0.1:6274/sse"
                #     async with sse_client(sse_url) as streams:
                #         print("SSE connection established.")
                #         read_stream, write_stream = streams
                #         async with ClientSession(read_stream, write_stream) as session:
                #             print("ClientSession created.")
                #             try:
                #                 print("--> Calling session.initialize()...")
                #                 await session.initialize() # <----- Explicit call added here!!!
                #                 await self.mcp.get_context().session.send_log_message("critical", "Session initialized successfully.")
                #                 print("<-- session.initialize() completed.")

                #                 # Now safe to proceed with tool calls
                #                 print("Session initialized, safe to call tools.")
                #                 try:
                #                     async with Client("http://127.0.0.1:6274", roots=["file:///Users/kushaldevgun/Downloads/images"]) as client:
                #                         # Call a tool on the server
                #                         result = await client.call_tool("create_file", {"path": img_path, "content": b64})
                #                         await self.mcp.get_context().session.send_log_message("critical", f"Tool call result: {result}")
                #                 except Exception as e:
                #                     logging.error(f"Error calling create_file tool: {e}")
                #                     await self.mcp.get_context().session.send_log_message("critical", f"Error calling create_file tool: {e}")
                #                     return text("Failed to save the generated chart image.", is_error=True)
                #                 # Example tool call:
                #                 # response = await session.call_tool("some_tool", {"arg": "value"})
                #                 # print(f"Tool response: {response}")

                #             except Exception as init_error:
                #                 print(f"Error during session.initialize(): {init_error}")
                # except Exception as conn_error:
                #     print(f"Connection error: {conn_error}")
                    
                return ImageContent(
                    type="image",
                    data=b64,
                    mimeType=mime
                )

            except Exception as e:
                logging.error(f"Error generating bar chart: {e}")
                await self.mcp.get_context().session.send_log_message("critical", f"Error generating bar chart: {e}")
                return text("Failed to generate bar chart.", is_error=True)

    def plot_pie_chart(self, session_state: PieChartSessionState) -> Dict[str, Any] | ImageContent:
        def decide_step(s: PieChartSessionState) -> str:
            if not s.table_name: return PieChartSteps.ASK_TABLE_NAME.value
            if not s.category_column: return PieChartSteps.ASK_CATEGORY_COLUMN.value
            return PieChartSteps.GENERATE_PIE_CHART.value

        session = PIECHARTSESSION.setdefault(session_state.session_id, session_state)
        if session_state.table_name: session.table_name = session_state.table_name
        if session_state.category_column: session.category_column = session_state.category_column
        
        session.step = decide_step(session)

        if session.step == PieChartSteps.ASK_TABLE_NAME.value:
            return {"status": "ask_table_name", "message": "Which table would you like to use for the pie chart?"}

        elif session.step == PieChartSteps.ASK_CATEGORY_COLUMN.value:
            if not PostgresHelperFxns(self.adapter).check_table_exists(session.table_name):
                PIECHARTSESSION.pop(session.session_id, None)
                return {"status": "error", "message": f"Table '{session.table_name}' does not exist."}
            return {"status": "ask_column", "message": "Which categorical column should define the pie slices?"}

        elif session.step == PieChartSteps.GENERATE_PIE_CHART.value:
            data = PostgresHelperFxns(self.adapter).fetch_column_data(session.table_name, session.category_column)
            if not data:
                return {"status": "error", "message": "No data found for visualization."}

            labels = [str(row[session.category_column]) for row in data]
            sizes = [row['count'] for row in data]

            try:
                plt.figure(figsize=(8, 8))
                plt.pie(sizes, labels=labels, autopct='%1.1f%%', startangle=140)
                plt.title(f'Distribution of {session.category_column} in {session.table_name}')
                
                path = f'/Users/kushaldevgun/Downloads/{session.session_id}_pie_chart.png'
                plt.savefig(path, format='png')
                plt.close()

                # Reuse your existing base64 encoding logic
                with open(path, "rb") as f:
                    b64 = base64.b64encode(f.read()).decode("utf-8")
                
                PIECHARTSESSION.pop(session.session_id, None)
                return ImageContent(type="image", data=b64, mimeType="image/png")
            except Exception as e:
                logging.error(f"Pie chart error: {e}")
                return {"status": "error", "message": f"Failed to generate pie chart. error: {e}"}
    
    def plot_histogram(self, session_state: HistogramSessionState) -> Dict[str, Any] | ImageContent:
        def decide_step(s: HistogramSessionState) -> str:
            if not s.table_name: return HistogramSteps.ASK_TABLE_NAME.value
            if not s.numeric_column: return HistogramSteps.ASK_NUMERIC_COLUMN.value
            return HistogramSteps.GENERATE_HISTOGRAM.value

        session = HISTOGRAMSESSION.setdefault(session_state.session_id, session_state)
        if session_state.table_name: session.table_name = session_state.table_name
        if session_state.numeric_column: session.numeric_column = session_state.numeric_column
        if session_state.bins: session.bins = session_state.bins
        
        session.step = decide_step(session)

        if session.step == HistogramSteps.ASK_TABLE_NAME.value:
            return {"status": "ask_table_name", "message": "Which table contains the numeric data for the histogram?"}

        elif session.step == HistogramSteps.ASK_NUMERIC_COLUMN.value:
            if not PostgresHelperFxns(self.adapter).check_table_exists(session.table_name):
                HISTOGRAMSESSION.pop(session.session_id, None)
                return {"status": "error", "message": f"Table '{session.table_name}' not found."}
            return {"status": "ask_column", "message": "Which numeric column would you like to analyze?"}

        elif session.step == HistogramSteps.GENERATE_HISTOGRAM.value:
            # Fetch raw data for the specific column
            query = f'SELECT "{session.numeric_column}" FROM "{session.table_name}" WHERE "{session.numeric_column}" IS NOT NULL;'
            results = self.adapter.execute_query(query)
            
            if not results:
                return {"status": "error", "message": "No numeric data found for this column."}

            data = [row[session.numeric_column] for row in results]

            try:
                plt.figure(figsize=(10, 6))
                plt.hist(data, bins=session.bins, color='skyblue', edgecolor='black')
                plt.title(f'Frequency Distribution of {session.numeric_column}')
                plt.xlabel(session.numeric_column)
                plt.ylabel('Frequency')
                
                path = f'/Users/kushaldevgun/Downloads/{session.session_id}_histogram.png'
                plt.savefig(path, format='png')
                plt.close()

                # Encode to base64 using established project patterns
                with open(path, "rb") as f:
                    b64 = base64.b64encode(f.read()).decode("utf-8")
                
                HISTOGRAMSESSION.pop(session.session_id, None)
                return ImageContent(type="image", data=b64, mimeType="image/png")
            except Exception as e:
                logging.error(f"Histogram error: {e}")
                return {"status": "error", "message": "Failed to generate histogram."}
        # """Display a sample dashboard with metrics."""
        # dashboard_html = f"""
        # <div style="padding: 20px; font-family: Arial, sans-serif;">
        #     <h1>Server Dashboard</h1>
        #     <img src="data:{mime};base64,{b64}" style="width:100%; height:auto; border-radius:12px; border:1px solid rgba(0,0,0,.12);" />
        # </div>
        # """
        
        # ui_resource = create_ui_resource({
        #     "uri": "ui://dashboard/main",
        #     "content": {
        #         "type": "rawHtml",
        #         "htmlString": dashboard_html
        #     },
        #     "encoding": "text",
        #     "uiMetadata": {
        #         UIMetadataKey.PREFERRED_FRAME_SIZE: ["800px", "600px"],

        #         }
        # })
        # return [ui_resource]

        return {"status": "error", "message": "Invalid step in histogram generation process."}

    async def show_new_dashboard(self) -> list[UIResource]:
        client = AcontextClient(api_key="sk-ac-HnRuhB0Z3i2xlrBAL26LN9ZUc9Wx2EHEhwGLNlr7BIk", )
        disk = client.disks.create()
        png_bytes = None
        with open('/Users/kushaldevgun/Downloads/images/bar_chart.png', "rb") as f:
            png_bytes = f.read()
            
        artifact = client.disks.artifacts.upsert(
            disk.id,
            file=FileUpload(filename="bar_chart.png", content=png_bytes),
            file_path="/images/",
            meta={"kind": "chart"}
        )

        # 3) Ask for a public URL explicitly
        result = client.disks.artifacts.get(
            disk.id,
            file_path="/images/",
            filename="bar_chart.png",
            with_public_url=True
        )
        

        uri = result.public_url
        await self.mcp.get_context().session.send_log_message("critical", f"Fetched image from Acontext with URI: {uri}")
        dashboard_html = f"""
        <div style="padding: 20px; font-family: Arial, sans-serif;">
            <h1>Server Dashboard</h1>
            <img src="{uri}" style="width:100%; height:auto; border-radius:12px; border:1px solid rgba(0,0,0,.12);" />
        </div>
        """
        ui = create_ui_resource({
            "uri": "ui://dashboard/main",
            "content": {
                "type": "rawHtml",
                "htmlString": dashboard_html
            },
            "encoding": "text",
            "uiMetadata": {
                UIMetadataKey.PREFERRED_FRAME_SIZE: ["800px", "600px"],
                }
        })
        return [ui]
    
        # img = PILImage.open('/Users/kushaldevgun/Downloads/images/bar_chart.png')
        # img.save('/mnt/user-data/uploads/bar_chart.png')
        # sandboxed_path = "/mnt/user-data/uploads/bar_chart.png"
        # mime, _ = mimetypes.guess_type(sandboxed_path)

#    def show_interactive_demo(self) -> list[UIResource]:
#         """Show an interactive demo with buttons that send intents."""
#         interactive_html = """
#         <div style="padding: 20px; font-family: Arial, sans-serif;">
#             <h2>Interactive Demo</h2>
#             <p>Click the buttons below to send different types of actions back to the parent:</p>
            
#             <div style="margin: 10px 0;">
#                 <button onclick="sendIntent('user_action', {type: 'button_click', id: 'demo'})" 
#                         style="background: #2563eb; color: white; padding: 8px 16px; border: none; border-radius: 4px; margin: 5px; cursor: pointer;">
#                     Send Intent
#                 </button>
#                 <button onclick="sendToolCall('get_data', {source: 'ui'})" 
#                         style="background: #059669; color: white; padding: 8px 16px; border: none; border-radius: 4px; margin: 5px; cursor: pointer;">
#                     Call Tool
#                 </button>
#             </div>
            
#             <div id="status" style="margin-top: 20px; padding: 10px; background: #f3f4f6; border-radius: 4px;">
#                 Ready - click a button to see the action
#             </div>
#         </div>
        
#         <script>
#             function sendIntent(intent, params) {
#                 const status = document.getElementById('status');
#                 status.innerHTML = `<strong>Intent sent:</strong> ${intent}<br><strong>Params:</strong> ${JSON.stringify(params)}`;
                
#                 if (window.parent) {
#                     window.parent.postMessage({
#                         type: 'intent',
#                         payload: { intent: intent, params: params }
#                     }, '*');
#                 }
#             }
            
#             function sendToolCall(toolName, params) {
#                 const status = document.getElementById('status');
#                 status.innerHTML = `<strong>Tool call:</strong> ${toolName}<br><strong>Params:</strong> ${JSON.stringify(params)}`;
                
#                 if (window.parent) {
#                     window.parent.postMessage({
#                         type: 'tool',
#                         payload: { toolName: toolName, params: params }
#                     }, '*');
#                 }
#             }
#         </script>
#         """
        
#         ui_resource = create_ui_resource({
#             "uri": "ui://demo/interactive",
#             "content": {
#                 "type": "rawHtml",
#                 "htmlString": interactive_html
#             },
#             "encoding": "text"
#         })
#         return [ui_resource]

# client = AcontextClient(api_key="sk-ac-HnRuhB0Z3i2xlrBAL26LN9ZUc9Wx2EHEhwGLNlr7BIk", )
            # disk = client.disks.create()
            # artifact = client.disks.artifacts.upsert(
            #     disk.id,
            #     file=FileUpload(filename="bar_chart_1.svg", content=png_bytes),
            #     file_path="/images/",
            #     meta={"kind": "chart"}
            # )

            # # 3) Ask for a public URL explicitly
            # result = client.disks.artifacts.get(
            #     disk.id,
            #     file_path="/images/",
            #     filename="bar_chart_1.svg",
            #     with_public_url=True
            # )
            # uri = result.public_url
            # await self.mcp.get_context().session.send_log_message("critical", f"Fetched image from Acontext with URI: {uri}")
            #img = PILImage.open('/Users/kushaldevgun/Downloads/images/bar_chart_1.png')
            # img.save('/mnt/user-data/uploads/bar_chart_1.png')
            # sandboxed_path = "/mnt/user-data/uploads/bar_chart_1.png"
            # mime, _ = mimetypes.guess_type(sandboxed_path)
   # def show_interactive_demo(self) -> list[UIResource]:
    #     """Show an interactive demo with buttons that send intents."""
    #     interactive_html = """
    #     <div style="padding: 20px; font-family: Arial, sans-serif;">
    #         <h2>Interactive Demo</h2>
    #         <p>Click the buttons below to send different types of actions back to the parent:</p>
            
    #         <div style="margin: 10px 0;">
    #             <button onclick="sendIntent('user_action', {type: 'button_click', id: 'demo'})" 
    #                     style="background: #2563eb; color: white; padding: 8px 16px; border: none; border-radius: 4px; margin: 5px; cursor: pointer;">
    #                 Send Intent
    #             </button>
    #             <button onclick="sendToolCall('get_data', {source: 'ui'})" 
    #                     style="background: #059669; color: white; padding: 8px 16px; border: none; border-radius: 4px; margin: 5px; cursor: pointer;">
    #                 Call Tool
    #             </button>
    #         </div>
            
    #         <div id="status" style="margin-top: 20px; padding: 10px; background: #f3f4f6; border-radius: 4px;">
    #             Ready - click a button to see the action
    #         </div>
    #     </div>
        
    #     <script>
    #         function sendIntent(intent, params) {
    #             const status = document.getElementById('status');
    #             status.innerHTML = `<strong>Intent sent:</strong> ${intent}<br><strong>Params:</strong> ${JSON.stringify(params)}`;
                
    #             if (window.parent) {
    #                 window.parent.postMessage({
    #                     type: 'intent',
    #                     payload: { intent: intent, params: params }
    #                 }, '*');
    #             }
    #         }
            
    #         function sendToolCall(toolName, params) {
    #             const status = document.getElementById('status');
    #             status.innerHTML = `<strong>Tool call:</strong> ${toolName}<br><strong>Params:</strong> ${JSON.stringify(params)}`;
                
    #             if (window.parent) {
    #                 window.parent.postMessage({
    #                     type: 'tool',
    #                     payload: { toolName: toolName, params: params }
    #                 }, '*');
    #             }
    #         }
    #     </script>
    #     """
        
    #     ui_resource = create_ui_resource({
    #         "uri": "ui://demo/interactive",
    #         "content": {
    #             "type": "rawHtml",
    #             "htmlString": interactive_html
    #         },
    #         "encoding": "text"
    #     })
    #     return [ui_resource]
        
    # async def plot_bar_chart(self,session_state: BarChartSessionState) -> Dict[str, Any] | CallToolResult:

    #     def decide_step(session_state: BarChartSessionState) -> str:
    #         has_table_name = bool(session_state.table_name)
    #         has_column_name = bool(session_state.column_name)
    #         if not has_table_name:
    #             return BarChartSteps.ASK_TABLE_NAME.value
    #         elif not has_column_name:
    #             return BarChartSteps.ASK_COLUMN.value
    #         else:
    #             return BarChartSteps.GENERATE_CHART.value

    #     session = BARCHARTSESSION.setdefault(session_state.session_id, session_state)
    #     if session_state.table_name is not None:
    #         session.table_name = session_state.table_name
    #     if session_state.column_name is not None:
    #         session.column_name = session_state.column_name
    #     #await self.mcp.get_context().session.send_log_message("critical", f"Current session state: {session}")
    #     session.step = decide_step(session)
        
    #     if session.step == BarChartSteps.ASK_TABLE_NAME.value:
    #         return {
    #             'status': 'ask_table_name',
    #             'message': 'Please provide the name of the table for which you want to generate the bar chart.'
    #         }
    #     elif session.step == BarChartSteps.ASK_COLUMN.value:
    #         result = PostgresHelperFxns(adapter=self.adapter).check_table_exists(session.table_name)  # Check if table exists, raise error if not
    #         if not result:
    #             BARCHARTSESSION.pop(session.session_id, None)  # Clear session on error
    #             return {
    #                 'status': 'error',
    #                 'message': f'Table "{session.table_name}" does not exist. Please check the table name and try again.'
    #             }
    #         return {
    #             'status': 'ask_column',
    #             'message': 'Please provide the column for which you want to generate the bar chart.'
    #         }
    #     elif session.step == BarChartSteps.GENERATE_CHART.value:
    #         column_data = PostgresHelperFxns(adapter=self.adapter).fetch_column_data(session.table_name, session.column_name)
    #         if not column_data:
    #             return {
    #                 'status': 'error',
    #                 'message': f'No data found for column "{session.column_name}" in table "{session.table_name}". Please check the table and its column name and try again.'
    #             }
            

    #         unique_values = [row[session.column_name] for row in column_data]
    #         counts = [row['count'] for row in column_data]
    #         # unique_values = np.unique(column_data)
    #         # counts = np.array([np.sum(column_data == val) for val in unique_values])    

    #         #Plotting the bar chart and saving it to a buffer
    #         try:
                
    #             plt.figure(figsize=(10, 6))
    #             plt.bar(unique_values, counts, color='blue')
    #             plt.xlabel(session.column_name, fontsize=12)
    #             plt.ylabel('Values', fontsize=12)
    #             plt.title('Bar Chart', fontsize=14)
    #             plt.tight_layout()
    #             path = f'/Users/kushaldevgun/Downloads/{session.session_id}_bar_chart.png'
    #             #plt.savefig(path, format = 'png')  # Save the chart as an image file

    #             buf = io.BytesIO()
    #             plt.savefig(buf, format='png', dpi=130)
    #             plt.close()  # Close the plot to free up memory
    #             buf.seek(0)
    #             b64 = base64.b64encode(buf.read()).decode()
    #             # Read the saved image and encode it in base64
    #             #b64 = base64.b64encode(buf.getvalue()).decode("utf-8")
    #             # return {
    #             #     "content": [
    #             #         {"type": "text", "text": f"Bar Chart - {session.column_name}"},
    #             #         {"type": "image", "data": b64, "mimeType": "image/png"}
    #             #         ]
    #             #     }   
    #             return CallToolResult(
    #                 content=[
    #                     TextContent(type="text", text=f"Bar Chart - {session.column_name}"),
    #                     ImageContent(type="image", data=b64, mimeType="image/png"),
    #                     ],
    #                     isError=False
    #                     )
    #             return PlotRenderTool(mcp=self.mcp).render_plot({
    #                 "image_path": path,
    #                 "title": f"Bar Chart - {session.column_name}"
    #                 })

    #             real_path = os.path.realpath(path)

    #             ALLOWED_DIR = "/Users/kushaldevgun/Downloads"
    #             # Restrict directory access
    #             if not real_path.startswith(os.path.realpath(ALLOWED_DIR) + os.sep):
    #                 raise ValueError("Access denied: path not allowed")

    #             if not os.path.isfile(real_path):
    #                 raise ValueError("File not found")

    #             mime, _ = mimetypes.guess_type(real_path)
    #             if not mime or not mime.startswith("image/"):
    #                 raise ValueError("Not a valid image")

    #             with open(real_path, "rb") as f:
    #                 blob = f.read()

    #             if len(blob) > 1_000_000:
    #                 raise ValueError("Image too large (>1MB)")

    #             b64 = base64.b64encode(blob).decode("utf-8")
    #             if b64 is None:
    #                 raise ValueError("Failed to encode image to base64")
                
    #             BARCHARTSESSION.pop(session.session_id, None)
    #             return ImageContent(
    #                 type="image",
    #                 data=b64,
    #                 mimeType=mime
    #             )
    #         except Exception as e:
    #             logging.error(f"Error generating bar chart: {e}")
    #             raise ValueError("Failed to generate bar chart.")
    #     else:
    #         return {
    #             'status': 'error',
    #             'message': 'Invalid step in bar chart generation process.'
    #         }

    # async def plot_bar_chart(self, session_state: BarChartSessionState) -> CallToolResult:

    #     def text(msg: str, is_error: bool = False) -> CallToolResult:
    #         return CallToolResult(
    #             content=[TextContent(type="text", text=msg)],
    #             isError=is_error,
    #         )

    #     def decide_step(session_state: BarChartSessionState) -> str:
    #         has_table_name = bool(session_state.table_name)
    #         has_column_name = bool(session_state.column_name)
    #         if not has_table_name:
    #             return BarChartSteps.ASK_TABLE_NAME.value
    #         elif not has_column_name:
    #             return BarChartSteps.ASK_COLUMN.value
    #         else:
    #             return BarChartSteps.GENERATE_CHART.value

    #     session = BARCHARTSESSION.setdefault(session_state.session_id, session_state)
    #     if session_state.table_name is not None:
    #         session.table_name = session_state.table_name
    #     if session_state.column_name is not None:
    #         session.column_name = session_state.column_name

    #     session.step = decide_step(session)

    #     if session.step == BarChartSteps.ASK_TABLE_NAME.value:
    #         return text("Please provide the name of the table for which you want to generate the bar chart.")

    #     if session.step == BarChartSteps.ASK_COLUMN.value:
    #         ok = PostgresHelperFxns(adapter=self.adapter).check_table_exists(session.table_name)
    #         if not ok:
    #             BARCHARTSESSION.pop(session.session_id, None)
    #             return text(f'Table "{session.table_name}" does not exist. Please check the table name and try again.', is_error=True)
    #         return text("Please provide the column for which you want to generate the bar chart.")

    #     if session.step == BarChartSteps.GENERATE_CHART.value:
    #         column_data = PostgresHelperFxns(adapter=self.adapter).fetch_column_data(session.table_name, session.column_name)
    #         if not column_data:
    #             return text(f'No data found for column "{session.column_name}" in table "{session.table_name}".', is_error=True)

    #         unique_values = [row[session.column_name] for row in column_data]
    #         counts = [row["count"] for row in column_data]

    #         try:
    #             plt.figure(figsize=(10, 6))
    #             plt.bar(unique_values, counts)
    #             plt.xlabel(session.column_name, fontsize=12)
    #             plt.ylabel("Values", fontsize=12)
    #             plt.title("Bar Chart", fontsize=14)
    #             plt.tight_layout()

    #             buf = io.BytesIO()
    #             plt.savefig(buf, format="png", dpi=130)
    #             plt.close()

    #             b64 = base64.b64encode(buf.getvalue()).decode("utf-8")

    #             BARCHARTSESSION.pop(session.session_id, None)
    #             html = f"""
    #             <!doctype html>
    #             <html>
    #             <head>
    #                 <meta charset="utf-8" />
    #                 <meta name="viewport" content="width=device-width, initial-scale=1" />
    #                 <style>
    #                 body {{
    #                     margin: 0;
    #                     padding: 16px;
    #                     font-family: system-ui, -apple-system, Segoe UI, Roboto, sans-serif;
    #                 }}
    #                 .wrap {{
    #                     display: flex;
    #                     flex-direction: column;
    #                     gap: 12px;
    #                 }}
    #                 img {{
    #                     width: 100%;
    #                     height: auto;
    #                     border: 1px solid rgba(0,0,0,0.12);
    #                     border-radius: 12px;
    #                 }}
    #                 h2 {{ margin: 0; font-size: 16px; }}
    #                 </style>
    #             </head>
    #             <body>
    #                 <div class="wrap">
    #                 <h2>Bar Chart - {session.column_name}</h2>
    #                 <img src="data:image/png;base64,{b64}" />
    #                 </div>
    #             </body>
    #             </html>
    #             """
    #             return CallToolResult(
    #                 content=[
    #                     {
    #                         "type": "image",
    #                         "resource": {
    #                             "uri": "ui://charts/app",
    #                             "mimeType": "text/html;profile=mcp-app",
    #                             "text": html,
    #         },
    #                     },
    #                     TextContent(type="text", text="Bar chart rendered."),
    #                     ],
    #                     isError=False
    #                     )
    #             # return CallToolResult(
    #             #     content=[TextContent(type="text", text="Bar chart rendered in panel.")],
    #             #     structuredContent={
    #             #         "kind": "plot",
    #             #         "title": f"Bar Chart - {session.column_name}",
    #             #         "mimeType": "image/png",
    #             #         "image_b64": b64,
    #             #     },
    #             #     isError=False
    #             #     )
    #         except Exception as e:
    #             logging.error(f"Error generating bar chart: {e}")
    #             return text("Failed to generate bar chart.", is_error=True)

    #     return text("Invalid step in bar chart generation process.", is_error=True)