class DashboardHelper:
    """A helper class for generating and managing dashboard-related content, such as creating HTML for dashboards and handling associated resources.
    """

    def generate_dashboard_html(self, svg_code: bytes) -> str:
        #Generates HTML content for a dashboard, embedding the provided SVG code.
        dashboard_html = f"""
            <!DOCTYPE html>
            <html lang="en">
            <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">

            <style>
                body {{
                    margin: 0;
                    padding: 40px;
                    background: linear-gradient(135deg, #eef2ff, #f8fafc);
                    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
                    display: flex;
                    justify-content: center;
                }}

                .dashboard-container {{
                    max-width: 900px;
                    width: 100%;
                    background: white;
                    border-radius: 16px;
                    padding: 32px;
                    box-shadow: 0 8px 24px rgba(0,0,0,0.08);
                    text-align: center;
                }}

                h1 {{
                    margin-bottom: 24px;
                    font-size: 28px;
                    color: #1f2937;
                }}

                .chart-wrapper {{
                    width: 100%;
                    overflow: hidden;
                }}

                .chart-wrapper svg {{
                    width: 100% !important;
                    height: auto !important;
                }}

                .footer {{
                    margin-top: 20px;
                    font-size: 12px;
                    color: #6b7280;
                }}
            </style>
            </head>

            <body>
                <div class="dashboard-container">
                    <h1>HR Performance Dashboard</h1>

                    <div class="chart-wrapper">
                        {svg_code.decode('utf-8')}
                    </div>
                    <div class="footer">Generated by Fig Orchestrator</div>
                </div>
            </body>
            </html>
            """
        return dashboard_html
    

# from mcp.server.fastmcp import FastMCP

# def resources(mcp: FastMCP):
#     @mcp.resource("ui://charts/app", mime_type="text/html;profile=mcp-app")
#     async def charts_app() -> str:
#         return """<!doctype html>
# <html>
# <head>
#   <meta charset="utf-8" />
#   <meta name="viewport" content="width=device-width, initial-scale=1" />
#   <style>
#     body { margin:0; padding:16px; font-family:system-ui; }
#     img { width:100%; height:auto; border-radius:12px; border:1px solid rgba(0,0,0,.12); }
#   </style>
# </head>
# <body>
#   <h3 id="title">Chart</h3>
#   <img id="img" />
#   <div id="status" style="opacity:.7;font-size:12px;margin-top:8px;">Waiting for data…</div>

#   <script>
#     // mcp-ui hosts send initial render data via postMessage
#     window.addEventListener("message", (event) => {
#       const msg = event?.data;
#       if (msg?.type === "mcp-ui-initial-render-data") {
#         const payload = msg.payload || {};
#         document.getElementById("title").textContent = payload.title || "Chart";
#         if (payload.pngBase64) {
#           document.getElementById("img").src = "data:image/png;base64," + payload.pngBase64;
#           document.getElementById("status").textContent = "✅ loaded";
#         } else {
#           document.getElementById("status").textContent = "❌ missing pngBase64";
#         }
#       }
#     });
#   </script>
# </body>
# </html>"""


# # from mcp.server.fastmcp import FastMCP
# # from tools.figureOchestrator.figOchestrationTools import CHART_IMAGE_BYTES

# # def resources(mcp: FastMCP):
# #     @mcp.resource("ui://charts/app", mime_type="text/html;profile=mcp-app")
# #     async def charts_app() -> str:
# #         return "<!doctype html><html><body><h3>Charts App OK</h3></body></html>"
# # def resources(mcp: FastMCP):
# #     @mcp.resource("ui://charts/app", mime_type="text/html;profile=mcp-app")
# #     async def charts_app() -> str:
# #         return """<!doctype html>
# #     <html>
# #     <head>
# #     <meta charset="utf-8" />
# #     <meta name="viewport" content="width=device-width, initial-scale=1" />
# #     <style>
# #         body { margin: 0; padding: 16px; font-family: system-ui; }
# #         img { width: 100%; height: auto; border-radius: 12px; border: 1px solid rgba(0,0,0,.12); }
# #     </style>
# #     </head>
# #     <body>
# #     <h3>Bar Chart</h3>
# #  <img id="plot" />
# #  <img src="http://127.0.0.1:8001/bar_chart_1.png" />
# #  <img src="file:///Users/kushaldevgun/Downloads/bar_chart_1.png" />
# # <script>
# #   const img = document.getElementById("plot");
# #   img.src = "file:///Users/kushaldevgun/Downloads/bar_chart_1.png";

# #   img.onload = () => document.body.insertAdjacentHTML("beforeend", "<p>✅ loaded</p>");
# #   img.onerror = () => document.body.insertAdjacentHTML("beforeend", "<p>❌ blocked / not found</p>");
# # </script>


# #     </body>
# #     </html>"""



# #     @mcp.resource("ui://charts/app", mime_type="text/html;profile=mcp-app")
# #     async def charts_app() -> str:
# #         return """<!doctype html>
# #         <html>
# #         <head>
# #         <meta charset="utf-8" />
# #         <meta name="viewport" content="width=device-width, initial-scale=1" />
# #         <style>
# #             body { margin: 0; padding: 16px; font-family: system-ui; }
# #             img { width: 100%; height: auto; border-radius: 12px; border: 1px solid rgba(0,0,0,.12); }
# #             .muted { opacity: .7; font-size: 12px; margin-top: 8px; }
# #             code { background: rgba(0,0,0,.06); padding: 2px 6px; border-radius: 6px; }
# #         </style>
# #         </head>
# #         <body>
# #         <h3 id="title">Bar Chart</h3>
# #         <div class="muted" id="status">Waiting for sid man…</div>
# #         <img id="plot" />

# #         <script>
# #   const sid = new URLSearchParams(location.search).get("sid");

# #   if (sid) {
# #     document.getElementById("plot").src =
# #       `ui://charts/image/${sid}.png`;
# #   } else {
# #     document.body.insertAdjacentHTML(
# #       "beforeend",
# #       "<p>Missing sid</p>"
# #     );
# #   }
# # </script>
# #         </body>
# #         </html>"""

#     # @mcp.resource("ui://charts/image/{sid}.png", mime_type="image/png")
#     # async def chart_image(sid: str) -> bytes:
#     #     with open(f"/tmp/{sid}.png", "rb") as f:
#     #         return f.read()

# #     async def charts_app() -> str:
# #         return """<!doctype html>
# # <html>
# # <head>
# #   <meta charset="utf-8" />
# #   <meta name="viewport" content="width=device-width, initial-scale=1" />
# #   <style>
# #     body { margin: 0; padding: 16px; font-family: system-ui; }
# #     img { width: 100%; height: auto; border-radius: 12px; border: 1px solid rgba(0,0,0,.12); }
# #   </style>
# # </head>
# # <body>
# #   <h3>Bar Chart</h3>
# #   <img id="plot" />
# #   <script>
# #     const sid = new URLSearchParams(location.search).get("sid");
# #     if (sid) {
# #       document.getElementById("plot").src = `ui://charts/image/${sid}.png`;
# #     } else {
# #       document.body.insertAdjacentHTML("beforeend", "<p>Missing sid</p>");
# #     }
# #   </script>
# # </body>
# # </html>"""

#     # @mcp.resource("ui://charts/image/{sid}.png", mime_type="image/png")
#     # async def chart_image(sid: str) -> bytes:
#     #     png_bytes = CHART_IMAGE_BYTES.get(sid)
#     #     if not png_bytes:
#     #         raise ValueError(f"No chart found for sid={sid}")
#     #     return png_bytes



# # resources/chartsResources.py
# # from pathlib import Path
# # from mcp.server.fastmcp import FastMCP
# # from mcp.types import TextResourceContents

# # def resources(mcp: FastMCP):
# #     # Use @mcp.resource(...) so FastMCP creates a Resource WITH a read() method internally.
# #     @mcp.resource("ui://charts/app", mime_type="text/html;profile=mcp-app")
# #     def charts_ui() -> TextResourceContents:
# #         html_path = Path(__file__).parent / "charts_app.html"
# #         html = html_path.read_text(encoding="utf-8")

# #         return TextResourceContents(
# #             uri="ui://charts/app",
# #             mimeType="text/html;profile=mcp-app",
# #             text=html,
# #         )


# # from pathlib import Path
# # from mcp.server.fastmcp import FastMCP
# # from mcp.types import TextResourceContents

# # class ChartsResources:
# #     def __init__(self, mcp: FastMCP):
# #         self.mcp = mcp

# #     # def get_charts_ui(self) -> str:
# #     #     html_path = Path(__file__).parent / "charts_app.html"
# #     #     return html_path.read_text(encoding="utf-8")

# # def resources(mcp: FastMCP):
# #     # res = ChartsResources(mcp = mcp)

# #     # Use @mcp.resource(...) so FastMCP creates a Resource WITH a read() method internally.
# #     @mcp.resource("ui://charts/app", mime_type="text/html;profile=mcp-app")
# #     def charts_ui() -> TextResourceContents:
# #         html_path = Path(__file__).parent / "charts_app.html"
# #         html = html_path.read_text(encoding="utf-8")
# #         return html
# #         # return TextResourceContents(
# #         #     uri="ui://charts/app",
# #         #     mimeType="text/html;profile=mcp-app",
# #         #     text=html,
# #         # )